# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
# enable_free_tier: true
tone_instructions: |
  Provide clear, concise, and professional feedback focused on improving documentation clarity, grammar, and consistency.
  Suggest improvements for readability and structure, and highlight any potential ambiguities.
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: true # testing 🙊
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
path_instructions:
  - path: "**/*.rst"
    instructions: |
      Review files for:
      - Consistent formatting (e.g., headings, lists, links).
      - Clear and concise language.
      - Correct grammar and spelling.
      - Proper use of rst syntax (e.g., avoid broken links or invalid code blocks).
      - Adherence to style guides (e.g., consistent tone, terminology).
      Suggest improvements to enhance readability and accessibility.
path_filters:
  - "!**/*.png"
chat:
  auto_reply: true
