name: publish docs
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup env
        run: pip install sphinxcontrib-applehelp==1.0.4 sphinxcontrib-devhelp==1.0.2 sphinxcontrib-htmlhelp==2.0.1 sphinxcontrib-qthelp==1.0.3 sphinxcontrib-serializinghtml==1.1.5 sphinx==4.2.0 sphinx-sitemap sphinx_code_tabs recommonmark git+https://github.com/codio/pydata-sphinx-theme.git@master

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: make html

      - name: Commit to deploy repo
        run: |
          mv html docs
          git config --global init.defaultBranch master
          git config --global user.name 'Max'
          git config --global user.email 'mkraev@codio.com'
          git init
          git remote add deploy https://MaximKraev:$GITHUB_TOKEN@github.com/codio/knowledge-deploy
          touch .nojekyll
          echo "docs.codio.com" > docs/CNAME
          git add .
          git commit -m "Automated deploy"
          git push -f deploy master
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        working-directory: build
