name: publish docs
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup env
        run: pip install sphinx==8.2.0 sphinxawesome-theme==5.3.2 sphinx-docsearch==0.1.0 sphinx-sitemap==2.9.0 sphinx_code_tabs==0.5.5 recommonmark==0.7.1

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: make html

      - name: Commit to deploy repo
        run: |
          mv html docs
          git config --global init.defaultBranch master
          git config --global user.name 'Max'
          git config --global user.email 'mkraev@codio.com'
          git init
          git remote add deploy https://MaximKraev:$GITHUB_TOKEN@github.com/codio/knowledge-deploy
          touch .nojekyll
          echo "docs.codio.com" > docs/CNAME
          git add .
          git commit -m "Automated deploy"
          git push -f deploy master
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        working-directory: build
